BEGIN TRANSACTION;

INSERT INTO users (username,password_hash,role) VALUES ('user','$2a$08$UkVvwpULis18S19S5pZFn.YHPZt3oaqHZnDwqbCW9pft6uFtkXKDC','ROLE_USER');
INSERT INTO users (username,password_hash,role) VALUES ('admin','$2a$08$UkVvwpULis18S19S5pZFn.YHPZt3oaqHZnDwqbCW9pft6uFtkXKDC','ROLE_ADMIN');

INSERT INTO breweries (brewery_name, contact_info, brewery_history, operating_hours, brewery_img_url, brewery_address) VALUES ('Autumn Arch', '(302) 294-1126', 'Local brewery located in Delaware. Opened in 2023.', 'Wed: 4-9pm, Thurs: 3-10pm, Fri: 12-10pm, Sat: 12-10pm, Sun: 12-8pm', 'https://www.autumnarch.com/', '810 Pencader Drive Suite C, Newark, DE, 19702');
INSERT INTO breweries (brewery_name, contact_info, brewery_history, operating_hours, brewery_img_url, brewery_address) VALUES ('Southern Ohio Brewing', 'https://www.southernohiobrewing.com/welcome-91521', 'Family owned and operated, Southern Ohio Brewing is a great place for getting together with family, friends or coworkers. We have 12-14 rotating taps featuring a wide range of  craft beer styles from our on-site brewhouse. Wine and our own house made hard seltzer are also available. ', 'Wed: 4-9pm, Thurs: 4-9pm, Fri: 3-10pm, Sat: 12-10pm, Sun: 12-8pm', 'https://images.squarespace-cdn.com/content/v1/5e8cbbecfb706f4f214ce102/c0376ed6-cf3b-4e49-b238-4977d9a3e5eb/taproom.jpg?format=2500w', '818 Factory Rd in Beavercreek, Ohio');
INSERT INTO breweries (brewery_name, contact_info, brewery_history, operating_hours, brewery_img_url, brewery_address) VALUES ('Miller Brewing Company', 'dataprotection@molsoncoors.com', 'In 1786, English immigrant John Molson founded Canada’s oldest beer brewery on the banks of the St. Lawrence River in Montreal. He wrote, “My beer has been universally well-liked beyond my most sanguine expectations.” The legacy continues seven generations later with brands like Molson Canadian, which was first brewed in 1959 and remains today one of Canada’s most iconic and best-selling beers.', 'Thurs: 10am-5pm, Fri: 10am-5pm', 'https://www.molsoncoors.com/sites/molsonco/files/2022-05/Brewery_Milwaukee_1920x768_v2.jpg', '4000 W. State Street • Milwaukee, WI 53208');
INSERT INTO breweries (brewery_name, contact_info, brewery_history, operating_hours, brewery_img_url, brewery_address) VALUES ('Iron Hill', '(302) 472-2739', 'Kevin Finn, one of those Delaware locals, receives a homebrewing kit from his wife for his wife for his birthday.What starts as a hobby soon becomes a passion', 'Mon: 11am-10pm, Tues: 11am-10pm, Wed: 11am-10pm, Thurs: 11am-10pm, Fri: 11am-10:30pm, Sat: 11am-10:30pm, Sun: 11am-9pm', 'https://olo-images-live.imgix.net/e5/e554bbcca77846af810dee6b4f618211.jpg?auto=format%2Ccompress&q=60&cs=tinysrgb&w=1500&h=1200&fit=crop&s=2d59b0229af19aa0db6062a156da616f', '620 JUSTISON ST WILMINGTON, DE 19801.');

COMMIT TRANSACTION;
