BEGIN TRANSACTION;

-- Created users to put it in the database
INSERT INTO users (username,password_hash,role) VALUES ('user','$2a$08$UkVvwpULis18S19S5pZFn.YHPZt3oaqHZnDwqbCW9pft6uFtkXKDC','ROLE_USER');
INSERT INTO users (username,password_hash,role) VALUES ('admin','$2a$08$UkVvwpULis18S19S5pZFn.YHPZt3oaqHZnDwqbCW9pft6uFtkXKDC','ROLE_ADMIN');

-- Created breweries to put in the database
INSERT INTO breweries (brewery_name, contact_info, brewery_history, operating_hours, brewery_img_url, brewery_address, brewery_city, brewery_state, brewery_zip, is_active) VALUES ('Autumn Arch', '(302)-294-1126', 'Local brewery located in Delaware. Opened in 2023.', 'Wed: 4-9pm, Thurs: 3-10pm, Fri: 12-10pm, Sat: 12-10pm, Sun: 12-8pm', 'https://s3-media0.fl.yelpcdn.com/bphoto/9UOIKbaZNCsSQ0f0Cwi2LA/348s.jpg', '810 Pencader Drive Suite C', 'Newark', 'DE', 19702, true);
INSERT INTO breweries (brewery_name, contact_info, brewery_history, operating_hours, brewery_img_url, brewery_address, brewery_city, brewery_state, brewery_zip, is_active) VALUES ('Volunteer Brewing Company', '(302)-464-0822', 'The Taphouse @ Volunteer Brewing is located on Main Street in the heart of downtown Middletown in a renovated home originally built in the early 1800’s. As a residence, the Main Street home has been host to countless family gatherings and precious family milestone’s through many generations. We welcome you to visit and make new memories with family and friends.', 'Mon-Wed: Closed, Thurs: 3pm-9pm, Fri: 3pm-10pm, Sat: Noon-10pm, Sun: Noon-6pm', 'https://static.wixstatic.com/media/e0b006_d311a4d758b04be4ba49eddf00db9e3f~mv2.jpg/v1/fill/w_214,h_184,al_c,q_80,usm_0.66_1.00_0.01,enc_auto/714E00CB-B640-47E9-B63A-61CD2C28A894_JPG.jpg', '116 W Main St', 'Middletown', 'DE', 19709, true);
INSERT INTO breweries (brewery_name, contact_info, brewery_history, operating_hours, brewery_img_url, brewery_address, brewery_city, brewery_state, brewery_zip, is_active) VALUES ('Brick Works Brewing and Eats', '(302)-508-2523', 'Brick Works Brewing & Eats was founded in 2016 in Smyrna, Delaware. Focused on producing the highest quality beverages and menu items, the brewpub prides itself on utilizing locally sourced ingredients for both its beers and its foods. For years, owners Ryan Maloney and Kevin Reading spoke about working on a project together. But, the right opportunity had not yet presented itself. Shortly after the fall of 2015, a property developer in Smyrna approached Reading with a restaurant location that could not be beaten, and thus came the concept of a brewpub.', 'Mon: 3-9pm, Tues: 3pm-9pm, Wed: 3pm-9pm, Thurs: 11am-9pm, Fri: 11am-10pm, Sat: 11am-10pm, Sun: 11am-9pm', 'https://static.spotapps.co/spots/57/d57588f7eb487dbbe34d797a3756d6/medium', '230 South Dupont Boulevard', 'Smyrna', 'DE', 19977, true);
INSERT INTO breweries (brewery_name, contact_info, brewery_history, operating_hours, brewery_img_url, brewery_address, brewery_city, brewery_state, brewery_zip, is_active) VALUES ('Iron Hill Brewery', '(302)-472-2739', 'Kevin Finn, one of those Delaware locals, receives a homebrewing kit from his wife for his wife for his birthday.What starts as a hobby soon becomes a passion', 'Mon: 11am-10pm, Tues: 11am-10pm, Wed: 11am-10pm, Thurs: 11am-10pm, Fri: 11am-10:30pm, Sat: 11am-10:30pm, Sun: 11am-9pm', 'https://assets.simpleviewinc.com/simpleview/image/upload/c_limit,q_75,w_1200/v1/crm/wilmington/RIVERFRONT_Iron-Hill-Brewery-Exterior-355995005056b3a_355997a2-5056-b3a8-495081b6d5a23b1e.jpg', '620 JUSTISON ST', 'Wilmington', 'DE', 19801, true);
INSERT INTO breweries (brewery_name, contact_info, brewery_history, operating_hours, brewery_img_url, brewery_address, brewery_city, brewery_state, brewery_zip, is_active) VALUES ('Revelation Craft Brewery Company', '(302)-212-5674', 'Local brewing company founded in 2019', 'Mon-Thurs: 11am-9pm, Fri-Sat: 11am-10pm, Sun: 11am-9pm', 'https://revbeer.com/wp-content/uploads/2021/03/Rev-Home-Page-PIc-Update.jpg.', '19841 CENTRAL STREET', 'REHOBOTH BEACH', 'DE', 19971, true);
INSERT INTO breweries (brewery_name, contact_info, brewery_history, operating_hours, brewery_img_url, brewery_address, brewery_city, brewery_state, brewery_zip, is_active) VALUES ('Blue Earl Brewery Company', '(302)-653-2337', 'The founder of our brewery Ronnie “Blue” Earl Price is a man of simple tastes, always on the hunt for great music, gourmet food, and exceptional craft beer. The simplicity of the blues had always drawn him in, the soulfulness, the earthiness of the style made him feel good inside. Barbecue is to food as blues is to music he would always say, nothing fast about the blues or barbecue, too fast with the blues and you lose the feeling, too fast with barbecue and, well, it just ain’t no good. Finding a good beer had always been a challenge. American beers had lost all their former goodness with mass production and mass marketing. They had lost the feeling. He decided that if it couldn’t be bought, he would have to brew it himself.', 'Mon: 12pm-6pm, Tues: 3am-9pm, Wed: 3pm-9pm, Thurs: 12pm-10pm, Fri: 12pm-11pm, Sat: 12pm-11pm, Sun: 12pm-6pm', 'https://blueearlbrewing.com/wp-content/uploads/2022/10/313515532_674164377465186_7189830740580515757_n-2048x1536.jpg', '210 Artisan Dr', 'Smyrna', 'DE', 19977, true);
INSERT INTO breweries (brewery_name, contact_info, brewery_history, operating_hours, brewery_img_url, brewery_address, brewery_city, brewery_state, brewery_zip, is_active) VALUES ('Dewey Beer Company', '(302)-329-9759', 'Dewey Beer Company opened its doors for the first time in 2009 with a desire to bring incredible craft brews to the First State.', 'Mon-Sun: 12pm-9pm', 'https://www.delawareonline.com/gcdn/presto/2021/01/14/PWIL/1db165d3-4064-4cde-a348-9cb81ebca681-IMG_4639.jpeg?crop=4031,2267,x1,y603&width=3200&height=1800&format=pjpg&auto=webp', '21241 Iron Throne Drive', 'Milton', 'DE', 19968, true);
INSERT INTO breweries (brewery_name, contact_info, brewery_history, operating_hours, brewery_img_url, brewery_address, brewery_city, brewery_state, brewery_zip, is_active) VALUES ('Fordham & Dominion Brewing Company', '(302)-678-4810', 'Based on our shared values and a common philosophy of quality brewing, Fordham and Dominion joined forces in 2007 and consolidated operations in 2009. The First State is now home to the Fordham & Dominion Brewing Co., where beer lovers from near and far are able to stop by, get to know us, and enjoy our handcrafted beer and soda. Our roots run deep throughout the Mid-Atlantic region and we remain dedicated to our craft.', 'Mon: Closed, Tues-Thurs: 3pm-8pm, Fri-Sat: 12pm-9pm, Sun: 1pm-6pm', 'https://www.visitdelaware.com/sites/default/files/styles/listing_slideshow/public/listing_images/profile/4150/0-pint-glass1-d6b69aaf5056b3a_d6b69bda-5056-b3a8-49603f0169dc03d8.jpg?itok=HFcj_xVb', '1284 McD Drive', 'Dover', 'DE', 19901, true);
INSERT INTO breweries (brewery_name, contact_info, brewery_history, operating_hours, brewery_img_url, brewery_address, brewery_city, brewery_state, brewery_zip, is_active) VALUES ('Crooked Hammock Brewery', '(302)-644-7837', 'How did we get here? Well at some point he had enough, and Rich Garrahan decided to ditch his suit and tie to build his own little slice of heaven.  Rich envisioned a place where his worries were left at the door. He wanted what a lot of us want at one time or another: He wanted an escape. For him, that means a big backyard with tons of yard games, plenty of homemade craft beer, and a never-ending cookout where the burgers are as good as the conversation.', 'Mon-Thurs: 11am-9pm, Fri-Sat: 11am-10pm, Sun: 11am-9pm', 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSOnEJyG1QDA1gpUbtpU38sxmyvZoUiRVnrC5Mk-Xb4CQ5vtLZAbd-SxxQbG2wTFFYieoY&usqp=CAU', '36707 Crooked Hammock Way', 'Lewes', 'DE', 19958, true);
INSERT INTO breweries (brewery_name, contact_info, brewery_history, operating_hours, brewery_img_url, brewery_address, brewery_city, brewery_state, brewery_zip, is_active) VALUES ('Argilla Brewing Company', '(302)-731-8200', 'Some foods were made to pair with a beer, like pizza. And Argilla Brewing is what happens when a couple of home brew do-it-yourselfers love that pairing and own a well-loved pizzeria. This nanobrewery uses a 1.5-barrel system on-site at Pietro’s Pizza. So, its brewers are constantly experimenting with new tastes and ideas.',  'Mon: 12-9pm, Tues: 12-9pm, Wed: 12-9pm, Thurs: 12-10pm, Fri: 12-10pm, Sat: 12-10pm, Sun: 12-10pm', 'https://www.visitdelaware.com/sites/default/files/styles/listing_slideshow/public/listing_images/profile/5294/0-argilla_web0_566ef1f1-5056-b3a8-491c4b7ea605c329.jpg?itok=pREJAtMt', '2667 Kirkwood Highway', 'Newark', 'DE', 19711, true);
INSERT INTO breweries (brewery_name, contact_info, brewery_history, operating_hours, brewery_img_url, brewery_address, brewery_city, brewery_state, brewery_zip, is_active) VALUES ('Musings Fermentation Underground', '(302)-722-5759', 'Established in 2022, Musings Fermentation Underground is a barrel-aged brewery that draws its inspiration from old world Belgian brewing traditions. Using locally sourced ingredients, our spontaneous fermentations are patiently aged to produce the finest blends of artisanal, wild and sour beers and kombucha you’ll ever enjoy.',  'Mon: 12-9pm, Tues: 12-9pm, Wed: 12-9pm, Thurs: 12-10pm, Fri: 12-10pm, Sat: 12-10pm, Sun: 12-10pm', 'https://musingsbrews.com/wp-content/uploads/2023/01/video.webp', '674 Pencader Drive', 'Newark', 'DE', 19711, true);
INSERT INTO breweries (brewery_name, contact_info, brewery_history, operating_hours, brewery_img_url, brewery_address, brewery_city, brewery_state, brewery_zip, is_active) VALUES ('Stitch House Brewery', '(302)-250-4280', 'Located among the lively N. Market Street in Downtown Wilmington, you will feel the true heart of the city at this spot. Including a savory menu to pair with one of their german style house-brewed beers, live music and creative atmosphere. Dining room & bar are open - walk-ins are welcome, and takeout and curbside available.',  'Mon: 11am-10pm, Tues: 11am-10pm, Wed: 11am-10pm, Thurs: 11am-10pm, Fri: 11am-10pm, Sat: 11am-10pm, Sun: 12-10pm', 'https://assets.simpleviewinc.com/simpleview/image/upload/c_fill,h_768,q_75,w_959/v1/crm/wilmington/30441102_1963349317040484_749484248557158400_n0-353b10255056b3a_353b10f8-5056-b3a8-49fc11606b77a146.jpg', '829 N. Market Street', 'Wilmington', 'DE', 19801, true);
INSERT INTO breweries (brewery_name, contact_info, brewery_history, operating_hours, brewery_img_url, brewery_address, brewery_city, brewery_state, brewery_zip, is_active) VALUES ('Dogfish Head Brewings & Eats', '(302)-226-2739', 'Located on the main shopping and entertainment strip in Rehoboth, the "pub," as it’s known among Dogfish aficionados, is thought of as the birthplace and soul of the famous brewery. There is an intriguing menu filled plus pub-only and hard-to-find Dogfish beer. There’s often live entertainment, pairing dinners, spirits tastings and much more.',  'Mon: 11am-10pm, Tues: 11am-10pm, Wed: 11am-10pm, Thurs: 11am-10pm, Fri: 11am-10pm, Sat: 11am-10pm, Sun: 11am-10pm', 'https://www.dogfish.com/files/media/inn/coworker-dinner-2017-3.jpg', '320 Rehoboth Avenue', 'Rehoboth Beach', 'DE', 19971, true);
INSERT INTO breweries (brewery_name, contact_info, brewery_history, operating_hours, brewery_img_url, brewery_address, brewery_city, brewery_state, brewery_zip, is_active) VALUES ('Wilmington Brew Works', '(302)-722-4828', 'Wilmington Brew Works is housed in a former laboratory with a alluring patio. The brewery makes t additional styles with innovative craftsmanship.  WBW aims to offer a wide range of styles and rotate their products frequently.  The beer hunter will rejoice in the opportunity to try something new in the family friendly local atmosphere.  Different offerings will highlight all types of fermentation; so whether you enjoy a crisp clean lager, a hazy IPA or a wild, funky, or tart beer, Wilmington Brew Works have what you seek.',  'Mon: 5-9pm, Tues: 5-9pm, Wed: 3-10pm, Thurs: 3-10pm, Fri: 12-10pm, Sat: 12-10pm, Sun: 12-6pm', 'https://assets.simpleviewinc.com/simpleview/image/upload/c_limit,q_75,w_1200/v1/crm/wilmington/PXL_20210521_204330481_9165B334-3182-44F0-89C9740363E6AB07_aeaa003c-add9-4e37-bd54a771e2823e2d.jpg', '3129 Miller Road', 'Wilmington', 'DE', 19802, true);
INSERT INTO breweries (brewery_name, contact_info, brewery_history, operating_hours, brewery_img_url, brewery_address, brewery_city, brewery_state, brewery_zip, is_active) VALUES ('Midnight Oil Brewing Company', '(302)-286-7641', 'Just by looking at the name of the brews and their social media you can tell that this brewery knows how to put the fun in craft beverage. Enjoy rotating food trucks, farmers markets, and lagers, IPAS, stouts and more that have brewed the midnight oil to be as good as they are.', 'Mon: 2-10pm, Tues: 2-10pm, Wed: 2-10pm, Thurs: 2-10pm, Fri: 11am-11pm, Sat: 11am-11pm, Sun: 11am-11pm', 'https://images.squarespace-cdn.com/content/v1/64dd0da0b207d0264cc424a1/1694457782678-3CPPIMY17YM1P6Y9JI68/850_6672.jpg?format=500w', '674 Pencader Drive', 'Newark', 'DE', 19702, true);
INSERT INTO breweries (brewery_name, contact_info, brewery_history, operating_hours, brewery_img_url, brewery_address, brewery_city, brewery_state, brewery_zip, is_active) VALUES ('Bellefonte Brewing Company', '(302)-407-6765', 'Just by looking at the name of the brews and their social media you can tell that this brewery knows how to put the fun in craft beverage. Enjoy rotating food trucks, farmers markets, and lagers, IPAS, stouts and more that have brewed the midnight oil to be as good as they are.', 'Mon: 2-10pm, Tues: 2-10pm, Wed: 2-10pm, Thurs: 2-10pm, Fri: 11am-11pm, Sat: 11am-11pm, Sun: 11am-11pm', 'https://www.visitdelaware.com/sites/default/files/styles/listing_slideshow/public/listing_images/profile/5748/0-bellefonte_brewing_web1_566f584d-5056-b3a8-497d580ea02bcfa1.jpg?itok=yAePz5HU', '3605 Old Capitol Trail', 'Wilmington', 'DE', 19808, true);
INSERT INTO breweries (brewery_name, contact_info, brewery_history, operating_hours, brewery_img_url, brewery_address, brewery_city, brewery_state, brewery_zip, is_active) VALUES ('Dew Point Brewing Company', '(302)-235-8429', 'Alexa Hoffman became interested in craft brewing while in college at the University of South Carolina in 2008. Alexa didn’t realize it would one day turn into a family business. Her brother, Cody Hoffman, who was 16 years old, would catch the bug while helping his father brew beer with the home brewing kit. The next couple stops in Cody’s journey were Twin Lakes Brewing Company in Greenville, DE and then 8-months in brewing school in England. A few months after returning from England, his father had an idea… In October 2013, after more than a year of searching for the right location for the brewery and tasting room, John came across a dilapidated building in the Garrett Snuff Mill complex, built in 1901. John instantly felt right at home because his family had lived near Yorklyn for the past 30 years.', 'Wed: 4-9pm, Thurs: 4-9pm, Fri: 3-10pm, Sat: 1-10pm, Sun: 1-8pm', 'https://images.squarespace-cdn.com/content/v1/58ae54b6579fb308719b3959/1492536372067-GRVOWNT9WJQ0MGHGVCA9/Dewpoint_generic.jpg?format=2500w', '2878 Creek Road', 'Yorklyn', 'DE', 19736, true);
INSERT INTO breweries (brewery_name, contact_info, brewery_history, operating_hours, brewery_img_url, brewery_address, brewery_city, brewery_state, brewery_zip, is_active) VALUES ('Thompson Island Brewing Company', '(302)-226-4677', 'Thompson Island Brewing Company is an independent craft brewery & restaurant that celebrates the Coastal Delaware lifestyle. Located in Rehoboth Beach, the brewery is named after an island in the Rehoboth Bay and is reminiscent of a beach picnic and bonfire of your childhood. The beer menu showcases Thompson Island original brews along with rotating taps featuring other local breweries. Our nationally recognized culinary team draws inspiration from local farms, beaches and bays and consistently serves beautiful, simple food and fresh homemade beer.', 'Mon: 11:30am-10pm, Tues: 11:30am-10pm, Weds: 11:30am-10pm, Thurs: 11:30am-10pm, Fri: 11:30am-10pm, Sat: 11:30am-10pm, Sun: 11:30am-10pm', 'https://images.squarespace-cdn.com/content/v1/5c8fab1193a6322d488120c9/1572276363231-PCFIG899HJAJBV0AZ7L4/yGt9FH3A.jpeg?format=2500w', '30133 Veterans Way', 'Rehoboth Beach', 'DE', 19971, true);
INSERT INTO breweries (brewery_name, contact_info, brewery_history, operating_hours, brewery_img_url, brewery_address, brewery_city, brewery_state, brewery_zip, is_active) VALUES ('Big Oyster Brewery', '(302)-644-2621', 'Look for the big red barn, and the brews bursting with great flavor. Enjoy tasty eats, tasty flights, and a spacious relaxing backyard view. Big Oyster is a must stop spot for oyster lovers, and unique brew lovers alike.', 'Mon: 11:30am-9pm, Tues: 11:30am-9pm, Weds: 11:30am-9pm, Thurs: 11:30am-9pm, Fri: 11:30am-9pm, Sat: 11:30am-9pm, Sun: 11:30am-9pm', 'https://cdn.craftbeer.com/wp-content/uploads/20200507105619/HartonAndrew-1-scaled.jpg', '1007 Kings Highway', 'Lewes', 'DE', 19958, true);


-- Created beers to put in the database
INSERT INTO beers (brewery_id, beer_name, beer_description, abv, ibu, beer_img_url, beer_type) VALUES (1, 'Pumpkin Loaf', 'It’s all the classic fall spices forged atop a smooth & respectable German Bock backbone.  Strong layers of pumpkin bread and autumn vibes fade into a sweet caramel finish.', 7.1, 35, 'https://vinepair.com/wp-content/uploads/2020/10/weask_pumpkinale_social.jpg', 'Ale'),
                                                                                                      (1, 'American Blonde', 'This blonde ale is a light and refreshing alternative to the domestic lager. Pours with a light copper color and a solid head. A clean yeast and malt profile, with a hint of honey from the malt.', 4.8, 15, 'https://assets.untappd.com/photos/2022_06_03/f3c230fd85300056c5ea7306f3c02a44_raw.jpg', 'Blonde Ale'),
                                                                                                      (1, 'Hallowed Winter', 'Incredibly dark and silky smooth, this enlightened Imperial Stout has a strong roasted malt backbone with a mild sweetness and lingering chocolate notes. As we enter this hallowed season, the nights are long, dark, and cold. But they’re also clear, majestic, and beautiful. Savor the winter with an eye towards spring (and a strong drink in hand).', 12.0, 20, 'https://assets.untappd.com/photos/2023_03_31/92e75446132428c3172febd021c7eb9f_raw.jpg', 'Stout - Imperial/Double'),
                                                                                                      (1, 'Supersaurus Rex', 'The Supersaurus is a somewhat obscure dinosaur (that looks nothing like our label, mind you), but it definitely sparks the nostalgia of our childhood fascination with those real, but seemingly mythical, creatures. Ultimately, we decided to give this beer a label that any parent would be proud to hang on their fridge.', 6.5, 35, 'https://assets.untappd.com/photos/2023_09_22/0c60c296a9588e876a995430f51e519a_raw.jpg', 'IPA - New England/Hazy'),

                                                                                                      (2, 'Bolaris Winter Ale', 'When the winter weather forecast calls for trouble you turn to Bolaris. Our new seasonal winter ale brewed in the style of a scotch wee-heavy. 9.2% ABV, a dark, malty body, a heavy dose of maple syrup, and a touch of cinnamon and vanilla will keep you warm through whatever old-man winter has in store', 9.2, 19, 'https://assets.untappd.com/photos/2023_02_18/b0e6525fce400cf3ae9b1730100c6379_640x640.jpg', 'Scotch Ale/Wee Heavy'),
                                                                                                      (2, 'Pickett Fence Double IPA', 'Our double IPA, malty with just the right hop balance. We blended Nugget, Citra, Zythos, Simcoe, and Pacifica hops for a distinct bitterness and unique aroma. A great beer to share with your neighbor', 8.1, 76, 'https://assets.untappd.com/photo/2023_02_18/75d6eb2f9dcd1601d369ae806e84a123_c_1249152815_raw.jpg', 'IPA-Imperial/Double'),
                                                                                                      (2, 'Belgian Amber/Dubbel Doink', 'Our take on the classic Belgian dubbel brewed in seclusion for centuries by monks. This version was brewed in a converted 2-car garage off an alley in Middletown using some very special ingredients from Acme…Nailed it', 7.3, 42, 'https://assets.untappd.com/photos/2019_08_31/d464ad2f320f56f02420cd0789c74b03_raw.jpg', 'Belgian Dubbel'),
                                                                                                      (2, 'Just a Small Town Gourd', 'This is one of our favorite beers to brew. We start with 60 pounds of roasted ‘autumn buckskin’ pumpkins grown in the fields of Middletown’s Filasky Farm. The grains include a balanced mix of pilsner, local Delaware 2-row barley, and Belgian specialty grains. We rounded out the brew with brown sugar, cinnamon, and pumpkin spice. This ale requires a little extra elbow grease but it’s uniquely Middletown, perfect for late October nights and on only tap for a limited time.', 8.0, 25, 'https://assets.untappd.com/photos/2023_09_25/a060022ede1d50f4bfb38ff71953f403_raw.jpg', 'Pumpkin/Yam Beer'),

                                                                                                      (3, 'Drop Trowel', 'Brewed and Dry Hopped with Citra, El Dorado and Cascade hops. This juicy, unfiltered IPA contains tropical and pithy grapefruit notes.', 6.7, 44, 'https://assets.untappd.com/photos/2023_09_26/9ed6b13b7c369b6fca4c4f4298f497ab_raw.jpg', 'IPA-American'),
                                                                                                      (3, 'Chocolate Covered Pretzel Stout', 'A stout brewed with salt, chocolate and wheat designed to embody the delights of a chocolate covered pretzel.', 4.0, 10, 'https://assets.untappd.com/photos/2023_09_26/9d99a56f33396da57eac9e6eb0cce809_raw.jpg', 'Stout-American'),
                                                                                                      (3, 'Citrus Mistress', 'She’s zesty and she knows it! This American Wheat was brewed with fresh lemon and lime zest to bring out a bright fruity/citrus flavor and aroma. It’s light body compliments the cornucopia of citrus flavors.', 5.6, 15, 'https://assets.untappd.com/photos/2023_09_26/f3d4b84ca51e7b7d09953d25e707bad7_raw.jpg', 'Wheat Beer-American Pale Wheat'),
                                                                                                      (3, 'Tiny Brick!', 'La Choby got physical and changed her look! Tiny Brick is a crisp and easy drinking lager for all weather. With a faint cereal aroma and a lightly sweet grainy flavor this beer will go down easy.', 5.3, 11, 'https://assets.untappd.com/photos/2023_09_06/2bca2c511ee5b362cdf15245c487ec11_raw.jpg', 'Lager-American Light'),

                                                                                                      (4, 'Iron Hill Light Lager', 'Our lightest beer. Brewed to give a crisp, clean, refreshing taste with very subtle malt and hop flavor.', 4.0, 10, 'https://media-cdn.tripadvisor.com/media/photo-m/1280/16/27/86/44/iron-hill-light-lager.jpg', 'Lager'),
                                                                                                      (4, 'POG Champ', 'Level up with our insanely drinkable passionfruit orange guava (POG) combination. The tropical fruit flavors and a touch of tartness make this beer a true champ.', 4.8, 9, 'https://assets.untappd.com/photos/2023_09_18/12698ad631063173bcaf5c1eea007bc4_raw.jpg', 'Sour Fruited'),
                                                                                                      (4, 'Das Boot', 'Prost! This bright, balanced classic combines delicate hop flavors and bitterness with a clean, dry finish. It’s traditional, in the best way possible.', 4.9, 35, 'https://assets.untappd.com/photos/2023_09_23/b468cde48c26a88c8027a8e1342f18d9_raw.jpg', 'Pilsner-German'),
                                                                                                      (4, 'Bedotter', 'This Belgian-style Tripel plays tricks on your senses with its easy-drinking notes of plum, spice, and banana. But do not be fooled by its pale color and crisp finish, this well-balanced beer is always looking to slyly stir up some fun. After all, "Bedotter" is the Flemish word for "trickster".', 9.0, 38, 'https://assets.untappd.com/photos/2023_09_24/396407111d3087afd05fd1bd960b16b4_raw.jpg', 'Belgian Tripel'),

                                                                                                      (5, 'Conan the Juiceman', 'This Barbarian yeast strain drives a beautiful natural stone fruit juicy aroma with a clean finish. Meanwhile we add in 3.5 pounds of hops per barrel in late addition and dry-hopping creating that great haze plus the tropical aromas from the Azacca, Mosaic and Mandarina Bavaria Hops. Oh me oh my!!', 7.0, 52, 'https://assets.untappd.com/photos/2023_09_07/430955c47c797bc4891269c1b0952662_raw.jpg', 'IPA-New England/Hazy'),
                                                                                                      (5, 'Mother-In-Law IPA', 'Patrick gave his mother in law hop plant rhizomes years ago. She planted those roots and has been growing hops ever since. Patrick used his mother in law`s cascade hops in his home brewed IPA and this beer is our production version of that recipe. This beer is brewed with a variety of select hops, which includes Mosaic, Cascade, Chinook, Summit and Mandarina Bavaria hops. It has great floral and citrus aroma and a nice crisp bitterness that does not linger.', 6.3, 55, 'https://assets.untappd.com/photos/2023_09_25/a060022ede1d50f4bfb38ff71953f403_raw.jpg', 'IPA-American'),
                                                                                                      (5, 'Downtown Donut Brown', 'This beer is our imperial brown ale. We had fun making this one and used over 400 pounds of grain, 7 different malts, brown sugar, maple sugar, a touch of cinnamon, and it has 2 dozen donuts in the mash given to us by our friends at The Fractured Prune. While this is or highest ABV at 7.6%, it is a nice almost dessert style beer without any high alcohol perception', 7.6, 27, 'https://assets.untappd.com/photos/2023_09_19/9a55492c21e2971fa4344e2bac6fe095_raw.jpg', 'Brown Ale-Imperial/Double'),
                                                                                                      (5, 'Cocoa Nut Joe Porter', 'A beautiful trifecta of a Porter composed of toasted coconut, pure liquid cacao - Cholaca, and cold pressed coffee extracted by local coffee shop Rise Up.', 5.2, 30, 'https://assets.untappd.com/photos/2023_09_26/ddef2c230a077a83733f791cae7b8e1a_raw.jpg', 'Porter-Other'),

                                                                                                      (6, 'Top Of The World', 'A rich and complex dark ale, roasty malt with deep dark fruit flavors, and a warming, bittersweet finish. This beer utilizes a complex blend of malts and hops. A winter warmer with notes of espresso, dark chocolate, nuts, dried fruits and booze!', 10.0, 10, 'https://assets.untappd.com/photos/2023_03_18/8977039465bb1fd3ee7975030317894d_raw.jpg', 'Stout-Imperial/Double'),
                                                                                                      (6, 'Black Satin', 'This exquisite Chocolate Hazelnut Porter exhibits rich dark chocolate, delicious hazelnut and malty righteousness. We infuse this beer with an abundance of organic raw cocoa nibs and 100% chocolate and hazelnut extracts. Pure decadence to savor sip after sip on a cold winter`s night. Dark brown in color with a superb nose and luscious flavor.', 6.9, 35, 'https://assets.untappd.com/photos/2023_06_30/73906427f34936eb20f23d5d17932066_raw.jpg', 'Porter-American'),
                                                                                                      (6, 'Body & Soul', 'This Scotch Ale, also known as "Wee Heavy” endures a long boil in the kettle for caramelization. Exhibiting a deep copper color and wonderful full body, this brew is a malt bomb in your mouth! Sláinte!', 8.3, 24, 'https://assets.untappd.com/photos/2023_05_13/5bb7222d32c769d8a18c4211f4f00f65_raw.jpg', 'Scotch Ale/Wee Heavy'),
                                                                                                      (6, 'Honeysuckle Rose', 'An elegant Belgian Blond Ale emerges into the mix at Blue Earl. This beer takes its name from "Honeysuckle Rose" a 1929 song composed by Fats Waller with lyrics by Andy Razaf, and inducted in the Grammy Hall of Fame in 1999. A moderate-strength golden ale that has a subtle Belgian complexity, slightly sweet flavors of orange and lemon, and a dry finish. Gold in color, the beer is brewed with Pilsner, Munich, and specialty malts, then hopped with Hallertauer and Liberty. A sensational Belgian flavor profile that’s assured to satisfy your soul!', 7.2, 10, 'https://media-cdn.tripadvisor.com/media/photo-m/1280/16/27/86/44/iron-hill-light-lager.jpg', 'Lager'),

                                                                                                      (7, 'Swishy Pants', 'Double Dry Hopped with Citra, Mosaic and Galaxy hops to create a hazy yet juicy citrus forward beer, perfect for and IPA lover.', 7.5, 30, 'https://assets.untappd.com/photos/2023_09_26/adb7d39a0759abb31ce555e07f4b5d10_raw.jpg', 'IPA-American'),
                                                                                                      (7, 'Secret Machine-Triple Berry', 'Soft, creamy and bursting with ripe berries.', 7.0, 15, 'https://assets.untappd.com/photos/2023_09_26/d8bf910caefe91a416ac07121d29b5c8_raw.jpg', 'Fruit Beer'),
                                                                                                      (7, 'Hot Wax', 'Brewed with Vic Secret and Galaxy. Plenty of wheat flakes and pilsen malts.', 8.5, 30, 'https://assets.untappd.com/photos/2023_09_19/528e0eb077f0f8c2ae81da36e59b1530_raw.jpg', 'IPA-New England/Hazy'),
                                                                                                      (7, 'Futuristic Future', 'The Future is here. Predictions of hovering juice vehicles and galactic tropical sensory travel have come to fruition. Brewed with Galaxy and Mosaic', 9.1, 65, 'https://assets.untappd.com/photos/2023_09_03/e1969c21dacfd2f3ca499a16ef35af27_raw.jpg', 'IPA-Imperial/Double'),

                                                                                                      (8, 'Oak Barrel Stout', 'Dominion Oak Barrel Stout raises the bar for American stouts. We use smoked and peated malts to create an intricate malt foundation. Willamette and Cascade hops balance the malt character and our method of dry hopping with vanilla beans and oak chips pushes the depth of our stout''s flavor spectrum even further.', 5.5, 30, 'https://assets.untappd.com/photos/2023_08_26/b86c8c3ae22d9eae262f1dbb49fe3901_640x640.jpg', 'Stout-American'),
                                                                                                      (8, 'Double D', 'Double D is a full-bodied Imperial India Pale Ale, flaunting sultry guava, mango, and tropical fruit aromas as a result of dry hopping with Citra, Zythos and Crystal hops. Brewed with light toasted malt and Bravo bittering hops, this double delights with smooth warming alcohols and a torrid finish. A daring draft, she is available in six-packs and on draft.', 8.0, 90, 'https://assets.untappd.com/photos/2023_07_08/05ddfd66cdac84ce38ca4c8666b77f6a_raw.jpg', 'IPA-Imperial/Double'),
                                                                                                      (8, 'Candi', 'Don’t be fooled by Candi’s golden appearance. This Belgian Tripel may taste of sugar and spice, but her beguiling introduction is far from nice, flirting with a covert 10% ABV', 10.0, 32, 'https://assets.untappd.com/photos/2023_08_12/abc985d36548384d62f7043cbd2c545c_raw.jpg', 'Belgian Tripel'),
                                                                                                      (8, 'Copperhead Ale', 'Copperhead Ale is Fordham’s flagship beer and an interpretation of the American Amber Ale. Caramelized malts give this beer its sweet flavor and signature copper hue. Bravo hops attribute a slight bitterness to the finish.', 5.0, 25, 'https://assets.untappd.com/photos/2023_09_02/0deebc94637c5a52557115f3f73ceb24_raw.jpg', 'Red Ale-American Amber/Red'),

                                                                                                      (9, 'Beach Escape', 'This crisp Session IPA is brewed with an abundance of Citra & El Dorado hops and ripe tangerine peel. One sip will lead you on an escape from the day-to-day.', 4.5, 16, 'https://assets.untappd.com/photos/2023_09_22/23181e40305f9d5821cc8f28cc8d6946_raw.jpg', 'IPA-Session'),
                                                                                                      (9, 'South To Somewhere', 'This deliciously balanced golden ale is lightly hopped and brewed with fresh coconut for a subtle, tropical flavor. Leave your worries behind and let the coconut carry you south…', 4.9, 18, 'https://assets.untappd.com/photos/2023_09_25/262288a3d0158427449c1f5df53dec21_raw.jpg', 'Golden Ale-Other'),
                                                                                                      (9, 'Wai Ola', 'Wai Ola, meaning "water of life" in Hawaiian, was precisely the vibe Head Brewer, Chris Wood was aiming to capture in developing this light, California style ale. This beer was meant to be easy drinking but packs tons of summer flavor, thanks to additions of not just coconut water, but roasted coconut flakes in multiple stages of the brewing process. Mahalo! Notes: pale ale, subtle coconut, hints of tropical and pine hops, strong coconut aroma.', 6.5, 20, 'https://assets.untappd.com/photos/2022_06_05/ba734f48fe6a8a388187b8c73c9eba2f_raw.jpg', 'California Common'),
                                                                                                      (9, 'Haulin'' Oats', 'What better way can you make your mustache''s dreams come true than by filling it with a creamy, satisfying stout? This dark roasted brew is heavy in body and color but light in its mouthfeel, thanks to being brewed with rolled oats and lactose, which gives it an underlying sweetness. Notes: Creamy mouthfeel, roasted malts, brewed with oatmeal.', 5.8, 18, 'https://assets.untappd.com/photo/2022_11_27/4299cad6818407ac2817e311675f5d0d_c_1224883579_640x640.jpg', 'Stout-Milk/Sweet'),

                                                                                                      (10, '7 Day IPA', 'Hazy & fruit juicy-this batch was dry hopped with a crazy amount of Eukanot hops', 6.5, 35, 'https://assets.untappd.com/photos/2023_08_26/ced6a254dab3bbc89a4b188216316300_640x640.jpg', 'IPA-New England/Hazy'),
                                                                                                      (10, 'Wavy Grainy', 'Toasted ale. Rich copper color from the addition of grains that were toasted in our own pizza ovens.', 5.7, 25, 'https://assets.untappd.com/photos/2022_06_16/585792cbd678c7823bf4fe188b4456fd_640x640.jpg', 'Red Ale-American Amber/Red'),
                                                                                                      (10, 'Sin City Stout', 'Notes of roast and citrus.', 5.5, 10, 'https://assets.untappd.com/photos/2021_07_10/44578fa7bc7e0fa8f98436829728cecc_raw.jpg', 'Stout-American'),
                                                                                                      (10, 'Flute Lupulin', 'Fruit Juicy Imperial India Pale Ale brewed with wildflower honey & and a blend of pacific northwest hops.', 8.5, 90, 'https://assets.untappd.com/photos/2020_04_14/edb1d845f61875f54dd31b1a74b72f57_raw.jpg', 'IPA-Imperial/Double'),

                                                                                                      (11, 'Shadow', 'This beer was brewed into a coolship for spontaneous fermentation, and then we added Saison yeast extracted from a 19th-century wooden beer barrel, part of an archaeological dig in Washington, D.C. It was aged in American oak barrels that previously held Chardonnay, with an addition of Brettanomyces bruxellensis wild yeast for the final fermentation. The result is a velvety smooth, medium body Saison with funky barnyard notes, a hint of woody tannins balanced with pleasant cherry tartness, and a subtle finish of Chardonnay. Brewed with malted barley, malted wheat, unmalted wheat, Munich malt, and aged Tettnanger hops.', 9.5, 25, 'https://assets.untappd.com/photos/2023_07_27/3cd508589c466c116337bcdb1072210d_raw.jpg', 'Farmhouse Ale-Saison'),
                                                                                                      (11, 'Texture', 'Beers like Flanders-style Red Ale are deeply geohistorical and place-based. We began filling a coolship to initiate the spontaneous fermentation. Texture was then aged in a combination of American and French Oak barrels that previously held a variety of different red wines in both Burgundy and Bordeaux style casks. Our Flanders-style Red Ale is reddish/burgundy in color with tan foam. It has a barnyard funky character in the aroma and flavor. Enjoy gentle, yet rustic acidity with hints of dark caramel and chocolate. Our red ale also has slight fruity notes of dates, figs, and pie cherries. Brewed with malted barley, unmalted wheat, Carmel malt, and aged Tettnanger and Cascade hops. Show Less', 10.2, 20, 'https://assets.untappd.com/photos/2023_07_27/6ee6db886f37fb3017475581217de0d6_raw.jpg', 'Sour-Flanders Red Ale'),

                                                                                                      (12, 'Big Stitch Nick', 'Pale Ale made with Pale and Caramalt malts anf Cascade, Amarilla, and Centenial hops.', 5.6, 40, 'https://assets.untappd.com/photos/2023_09_03/b6267aec694bbdd9fbe6a9f011c6aed8_raw.jpg', 'Pale Ale-American'),
                                                                                                      (12, 'Snitchez Get Stitchz', 'Malt: Pale Munich Hops: Hallertau Mittlefruh', 8.5, 70, 'https://assets.untappd.com/photos/2023_08_02/0f602820acc909aa52f3124c26560ccd_640x640.jpg', 'IPA-Imperial/Double'),
                                                                                                      (12, 'Sho Nuff Stout', 'Malt: pale, roasted barley, chocolate. Hops: black, crystal.', 7.5, 15, 'https://assets.untappd.com/photos/2023_07_08/53670639f3e8e613cd8f7cf3a98bad97_640x640.jpg', 'Stout-Other'),
                                                                                                      (12, 'Rye Knot?', 'Rye IPA made with Pale, Rye, and Pale Crystal malts as well as Chinook, Bravo, and Mosiac hops.', 7.5, 58, 'https://assets.untappd.com/photos/2023_09_03/d2a89667bc271694456ae129329d244e_raw.jpg', 'IPA-Rye'),

                                                                                                      (13, 'Amazön Lederhösen', 'Brewed with all German Munich malt, noble hops and lager yeast, Amazön Lederhösen is a traditional märzen beer that''s filled with luscious layers of maltiness. The perfect pint for the season, its aromas and flavors will have you thinking you''re right there, at the largest beer drinking event in the world ... Oktoberfest in Germany! So grab your glass (or stein) and raise it high! Prost to good beer and happy times!', 5.3, 25, 'https://assets.untappd.com/photos/2023_09_25/a9a68c8135c93525df4fdae701a29046_raw.jpg', 'Märzen'),
                                                                                                      (13, 'Smooth Jamz', 'As fall approaches, thoughts of cooler nights and stouts start to creep In. With that in mind we wanted to give you something that would be good in the heat of the day and the cool evenings. This beer accomplishes that with its roasty cocoa notes from the dark malts and hints of a fall strawberry preserves from the hops and yeast with the smoothness of a Nitro pour.', 6.4, 59, 'https://assets.untappd.com/photos/2023_09_24/903ef416186ebe41ba20b89f2284eb03_640x640.jpg', 'Stout-American'),
                                                                                                      (13, 'Slightly Mighty', 'A lo-cal IPA that is slight in cals and carbs with mighty hop flavor! Slightly Mighty has all the flavor and tropical aromas of a world class IPA, but with only 95 calories, 3.6g carbs, 1g protein and 0g fat. Brewed with locally-grown barley, and a touch of monk fruit that delivers body and complexity but adds zero calories or carbs, Slightly Mighty is light-bodied and offers a lingering balanced sweetness.', 4.0, 30, 'https://assets.untappd.com/photos/2023_09_26/7b133dcaa8f56a463af36a1679c5108a_raw.jpg', 'IPA-Session'),
                                                                                                      (13, 'BoDeGose', 'Together with our pals at Talea Beer Co. We explored Brooklyn bodegas to discover an amazing bounty of beautiful ingredients. This small batch sour beer features ripe cherries & exotic guava accented by the earthy spice of pink peppercorns.', 5.0, 7, 'https://assets.untappd.com/photos/2023_09_25/d7d26ddd4f7958f3debf3f9e7431e209_raw.jpg', 'Sour-Fruited Gose'),

                                                                                                      (14, 'Lupulin Enlightenment', 'An enlightening blend of simcoe and mosaic hops with a heavy dose of oats and lactose. This beer remains sweet with the suggestion of apricot puree and tropical fruit. This moment of enlightenment is our inaugural dip into deep hoppy goodness.', 7.3, 36, 'https://assets.untappd.com/photos/2023_05_21/84ffb0a6579b32fe9e2c2fc3a336af58_raw.jpg', 'IPA-Milkshake'),
                                                                                                      (14, 'Superfluous Nomenclature', 'A Modern Pale Ale in the East Coast tradition. Dry-hopped with a classic combination of Amarillo, Citra and Nugget hops, this beer presents hop forward sensibilities with a refreshing citrus finish.', 4.8, 40, 'https://assets.untappd.com/photos/2023_06_17/506a982e8571e2afba9ac3560270a674_640x640.jpg', 'Pale Ale-American'),
                                                                                                      (14, 'Krauch''s Creation', 'During the 1850''s, a new style of beer was introduced in Delaware. A crisp, clean, cold fermented beer that would revolutionize brewing. This is our homage to the creator of the first lager beers in Delaware, Christian Krauch. This is a simple grain bill, with a light hop profile that is approachable by all!', 4.2, 10, 'https://assets.untappd.com/photos/2023_07_22/3278edbb478587a77b684ba78064d9ca_640x640.jpg', 'Lager-Helles'),
                                                                                                      (14, 'Eloquation', 'A mind numbing blend of honey and victory malts. The suggestion of orange blossoms is due to an addition of honey and a delicious combination of citra, simcoe and nugget dry hopping. NOTE: Eloquation is a legal SCRABBLETM move in our taproom! (20 Points)', 11.9, 100, 'https://assets.untappd.com/photos/2023_09_02/11111cedc1f6e9a596e41ad7c037eeb2_raw.jpg', 'IPA-Triple'),

                                                                                                      (15, 'XII APA', 'Perfectly sessionable ale with aroma of orange peel and bread, citrus throughout, sticky hops and biscuit finish.', 5.3, 37, 'https://assets.untappd.com/photos/2023_07_26/760b1812bbed0b76c1ae8a68dd7b8090_raw.jpg', 'Pale Ale-American'),
                                                                                                      (15, 'Midnight Porter', 'Our award winning porter starts coffee and chocolate on the nose and finishes with a chocolate covered toffee.', 4.5, 26, 'https://assets.untappd.com/photos/2022_11_20/a7523e05d26ab7d8a0f01338f1747a1e_640x640.jpg', 'Porter-English'),
                                                                                                      (15, 'Your Mom', 'A blonde ale brewed for our brewer’s mother, made with 300 pounds of raspberries, vanilla beans and lactose. It’s refreshing, it’s light, and its perfect for cooling off on a hot day.', 4.5, 17, 'https://assets.untappd.com/photos/2023_07_17/24b460ef00eec2c5e114299672efc4e7_640x640.jpg', 'Fruit Beer'),
                                                                                                      (15, 'Sundown Saison', 'A classic Saison with notes of sage, banana, lemon zest, and a hint of cracked pepper.', 5.7, 29, 'https://assets.untappd.com/photos/2023_08_12/3d246c41d036f4bac51c0c6f0b606c20_raw.jpg', 'Farmhouse Ale-Saison'),

                                                                                                      (16, 'Orange Street Ale', 'One of our flagships, this easy drinker combines a classic cream ale with Orange blossom honey and sweet orange peel to create a delicious and refreshing beer.', 5.8, 20, 'https://assets.untappd.com/photos/2023_09_20/c5e1126b1869c39f5f26ea0676859d97_640x640.jpg', 'Cream Ale'),
                                                                                                      (16, 'Small Wonder IPA', 'Taking from our states nickname, this IPA my be light in alcohol but packs a big hop punch!', 5.0, 40, 'https://assets.untappd.com/photos/2023_08_23/d9ef73249374e5416a5145160dd7d1a7_640x640.jpg', 'IPA-American'),
                                                                                                      (16, 'Oat-Face Killah', 'Straight back to the 36 chambers of hops plus lots of oats.', 6.6, 55, 'https://assets.untappd.com/photos/2023_09_16/167cb69d8e54f10e8809679f33af39bd_raw.jpg', 'IPA-New England/Hazy'),
                                                                                                      (16, 'Kiamensi Kolsch', 'A light crisp lager-like ale. Brewed with pilsner malt and German noble hops for a clean refreshing beer.', 5.0, 27, 'https://assets.untappd.com/photos/2023_06_10/c7ec55f52b36c36115c4dbd5d4bf4604_640x640.jpg', 'Kölsch'),

                                                                                                      (17, 'Hopworts Express', 'Tropical flavor, w/ passion fruit,guava,lime,pine, citrus. Smooth.', 6.5, 60, 'https://assets.untappd.com/photos/2023_08_20/5ca8954d150f9cd44e593732752d3ca6_640x640.jpg', 'IPA-American'),
                                                                                                      (17, 'Nit Wit', 'A traditional Belgian White Beer (Witbier) crafted with mixture of pale and wheat malts. Czech Kazabek Hops, and a mixture of unique spices. Classic Belgian whit yeast will yield a spicy, low Phenolic flavor.', 5.0, 17, 'https://assets.untappd.com/photos/2023_04_23/e5cfed56119f4ae210e4994a808b2687_640x640.jpg', 'Wheat Beer-Witbier/Blanche'),
                                                                                                      (17, 'Black Powder', 'Imperial Black IPA with Maris Otter, roasted and chocolate malts; and Summit, Centennial, Chinook, and local Cascade hops.', 10.4, 85, 'https://assets.untappd.com/photos/2023_07_22/9ae0facc4481ba3e1b96dabe78888e45_raw.jpg', 'IPA-Imperial/Double Black'),
                                                                                                      (17, 'Dubbel Dip', 'Very flavorful, lots of things going on in this beer. Malty,plum & dark fruit flavor', 7.1, 25, 'https://assets.untappd.com/photos/2023_08_26/34dedec9019115c7f3434c247a551eda_raw.jpg', 'Belgian Strong Dark Ale'),

                                                                                                      (18, 'No Bad Days', 'Southern Delaware Style Lager. Crisp with light citrus notes.', 6.0, 18, 'https://assets.untappd.com/photos/2023_08_23/da63804ebe7fe07bc3f9fb7e240edfbd_640x640.jpg', 'Lager-American'),
                                                                                                      (18, 'Cosmic Cow Milk Stout', 'A not-too-thick sweet stout. A heavily dark beer with a tan head floating on top. Opening the aroma is chocolate with hints of coffee and roasted malt. The palate starts off with baking chocolate with notes of coffee and roasted grain, slight toffee and malty sweetness in the background. All on a filling mouthfeel without being overly heavy.', 6.5, 20, 'https://assets.untappd.com/photos/2023_09_16/bb80aae40532dc2ddc846c507d9cfd08_640x640.jpg', 'Stout-Milk/Sweet'),
                                                                                                      (18, 'Glazed And Confused', 'Together, beer and donuts create Glazed & Confused, our latest pastry stout. Brewed with cacao nibs, lactose, vanilla, and actual donuts, we''re looking at the perfect breakfast beer.', 8.0, 36, 'https://media-cdn.tripadvisor.com/media/photo-m/1280/16/27/86/44/iron-hill-light-lager.jpg', 'Stout-Pastry'),
                                                                                                      (18, 'Boat Day White IPA', 'Refreshing wheat ale with lemon zest and orange peel hop notes.', 5.0, 45, 'https://assets.untappd.com/photos/2023_09_10/47b08e8053c3ffa2d43cd6b9eec39c6f_640x640.jpg', 'IPA-White/Wheat'),

                                                                                                      (19, 'Solar Power', 'Brewed with organic oranges and coriander, this beer is great for boats, beaches, and all things wonderful that come with warm weather. We cold steep this beer with the zest from the oranges used in the brewing process to give it a zesty aroma. It’s got a great nose that gives way to a light and refreshing finish', 6.0, 10, 'https://assets.untappd.com/photos/2023_09_10/ce26a5cdc98af5003ef6dfd027a46076_640x640.jpg', 'Wheat Beer-Witbier/Blanche'),
                                                                                                      (19, 'Noir et Bleu', 'Big Oyster Brewery Fan Favorite, the Noir et Bleu isn’t just your standard Belgian Tripel. Cold steeped with dried blueberries and black tea from the Spice and Tea Exchange in Rehoboth Beach, this beer provides a pleasant aroma of blueberry with just a hint of black tea on the back of the palate. This beer is both complex and deceivingly crushable. This beer is also a favorite of Big Oyster Staff! It’s a wonderful beer to enjoy during any time of year, and is a great introductory beer for wine drinkers into the quickly growing craft beer scene!', 9.0, 10, 'https://assets.untappd.com/photos/2023_09_23/56c1982a591a5f95b281b28a84811d4a_640x640.jpg', 'Belgian Tripel'),
                                                                                                      (19, 'On Point', 'Rich coffee stout steeped on "Big Oyster Brewski" coffee beans collabed & roasted at "BrewHaha!" coffee house in Wilmington, Delaware. The "Big Oyster Brewski" coffee roast is a special blend we hand selected and tasted by combining two of BrewHaha''s House Blends coming from South America. You get notes of chocolate and vanilla to round out this delicious, coffee forward brew.', 7.0, 25, 'https://assets.untappd.com/photos/2023_09_24/efe778fae9ec12620907893ab1f98d1b_raw.jpg', 'Stout-Milk/Sweet'),
                                                                                                      (19, 'Atlantico', 'This light crisp and refreshing beer will leave you longing for another .. Brewed with Pilsner malt and flaked maize to produce a subtle crispness and clean finish.', 4.4, 12, 'https://assets.untappd.com/photos/2023_09_25/d5504771dbe523dde79fe47279abd3e2_raw.jpg', 'Lager-Mexican'),
                                                                                                      (19, 'Shuck It', 'Oyster stout is an ode to our name Big Oyster Brewery. Historically, Oyster Stout began in the late 1800s when brewers found out that the shell of an oyster is packed with calcium carbonate, which could be used to purify and improve the beer while brewing. We at Big Oyster are keeping the tradition of Oyster Stout alive by adding our own spin on it to make this beer a rich and roasty sweet stout brewed with locally harvested oysters. Hints of dark chocolate and toasty bread will satisfy even the most sophisticated taste buds.', 6.2, 44, 'https://assets.untappd.com/photos/2023_09_20/85d044442a85ed6dda7b0cc92ff63815_raw.jpg', 'Stout-Oyster');




--Created beer reviews
INSERT INTO reviews (beer_id, star_rating, review_comments) VALUES (1, 5, 'This beer is perfect for the fall. It made me feel warm and cozy.');
INSERT INTO reviews (beer_id, star_rating, review_comments) VALUES (1, 3, 'Pumpkin Loaf is alright, but this place should just stick to the classic flavors we all know and love.');
INSERT INTO reviews (beer_id, star_rating, review_comments) VALUES (1, 5, 'BBE. Best. Beer. Ever');
INSERT INTO reviews (beer_id, star_rating, review_comments) VALUES (13, 5, 'My all time favorite beer. I recommend it to all beer lovers');
INSERT INTO reviews (beer_id, star_rating, review_comments) VALUES (13, 1, 'Disgusting. Wouldn''t drink it again, if you paid me.');
INSERT INTO reviews (beer_id, star_rating, review_comments) VALUES (13, 4, 'Subtle, yet strong. Just the way I like it.');
INSERT INTO reviews (beer_id, star_rating, review_comments) VALUES (2, 4, 'Mediocre.');
INSERT INTO reviews (beer_id, star_rating, review_comments) VALUES (2, 2, 'Not the worst I''ve ever had.');
INSERT INTO reviews (beer_id, star_rating, review_comments) VALUES (2, 5, 'This beer is just a classic. Plain and simple.');
INSERT INTO reviews (beer_id, star_rating, review_comments) VALUES (3, 1, 'The name is fitting. This beer reminds me a dark, cold place I do not want to visit.');
INSERT INTO reviews (beer_id, star_rating, review_comments) VALUES (3, 1, 'You might as well drink toilet water if you''re thinking of trying this.');
INSERT INTO reviews (beer_id, star_rating, review_comments) VALUES (3, 4, 'Par for the course.');
INSERT INTO reviews (beer_id, star_rating, review_comments) VALUES (4, 4, 'Super close to being one of my favorites, but not quite there yet.');
INSERT INTO reviews (beer_id, star_rating, review_comments) VALUES (4, 3, 'Only tried this beer for the name. Nothing to write home about.');
INSERT INTO reviews (beer_id, star_rating, review_comments) VALUES (4, 1, 'Just as the name implies, this beer is childish. Give me something strong.');
INSERT INTO reviews (beer_id, star_rating, review_comments) VALUES (5, 1, 'Bolaris? More like Yuck-aris!.');
INSERT INTO reviews (beer_id, star_rating, review_comments) VALUES (5, 2, 'Meh, it''s not the worst. The recipe could use some revamping for sure.');
INSERT INTO reviews (beer_id, star_rating, review_comments) VALUES (5, 5, 'Would rate this 10 stars if I could!');
INSERT INTO reviews (beer_id, star_rating, review_comments) VALUES (7, 3, 'This beer needs to pick a vibe and stick to it.');
INSERT INTO reviews (beer_id, star_rating, review_comments) VALUES (7, 4, 'Fantastic beer.');
INSERT INTO reviews (beer_id, star_rating, review_comments) VALUES (7, 2, 'I''ve tasted much better than this.');
INSERT INTO reviews (beer_id, star_rating, review_comments) VALUES (6, 5, 'Makes me feel like I''m at home having a grand old time.');
INSERT INTO reviews (beer_id, star_rating, review_comments) VALUES (6, 1, 'Worst tasting drink I''ve ever had.');
INSERT INTO reviews (beer_id, star_rating, review_comments) VALUES (6, 3, 'Not a fan of IPAs to be honest, but this one isn''t half bad.');
INSERT INTO reviews (beer_id, star_rating, review_comments) VALUES (8, 2, 'Does not do the song justice.');
INSERT INTO reviews (beer_id, star_rating, review_comments) VALUES (8, 3, 'Almost as good as the Journey song.');
INSERT INTO reviews (beer_id, star_rating, review_comments) VALUES (8, 5, 'I''m just a small town girl who loves this beer.');
INSERT INTO reviews (beer_id, star_rating, review_comments) VALUES (9, 5, 'This beer is heaven in a glass.');
INSERT INTO reviews (beer_id, star_rating, review_comments) VALUES (9, 1, 'I''m at a loss for words. Not in a good way.');
INSERT INTO reviews (beer_id, star_rating, review_comments) VALUES (9, 3, 'Would have liked a higher abu.');
INSERT INTO reviews (beer_id, star_rating, review_comments) VALUES (10, 1, 'Wish I was having pretzels instead of this..');
INSERT INTO reviews (beer_id, star_rating, review_comments) VALUES (10, 3, 'This beer is a hit with my friends.');
INSERT INTO reviews (beer_id, star_rating, review_comments) VALUES (10, 4, 'Just like reaching for pretzels, I couldn''t stop reaching for another sip of this drink.');
INSERT INTO reviews (beer_id, star_rating, review_comments) VALUES (11, 2, 'Feels like I''m on vacation with every sip.');
INSERT INTO reviews (beer_id, star_rating, review_comments) VALUES (11, 4, 'Unexpected delight.');
INSERT INTO reviews (beer_id, star_rating, review_comments) VALUES (11, 4, 'It''s a bittersweet beer.');

INSERT INTO reviews (beer_id, star_rating, review_comments) VALUES (12, 5, 'Tiny Brick is a splendid beer.'),
                                                                    (12, 4, 'Not too bitter, not too sweet.'),
                                                                    (12, 1, 'Yummy yummy in my tummy.'),
                                                                    (14, 5, 'This brew takes your taste buds on a wild hoppy ride. The citrusy notes are like a burst of sunshine in every sip.'),
                                                                    (14, 2, 'It''s like a pinecone in a glass. Not my cup of tea... or beer.'),
                                                                    (14, 1, 'I was expecting a burst of citrus, but it was more like a faint hint. It left me craving more flavor. It''s not as refreshing as it claims to be.'),
                                                                    (15, 4, 'It''s rich, velvety, and full of flavor.'),
                                                                    (15, 2, 'The notes were just too intense. I prefer something lighter.'),
                                                                    (15, 5, 'It''s like a beach vacation for your taste buds.'),
                                                                    (16, 5, 'It''s a safe choice if you''re not looking for anything too adventurous'),
                                                                    (16, 3, 'It''s drinkable, but I wouldn''t go out of my way to order it again'),
                                                                    (16, 4, 'It''s worth trying if you''re into barrel-aged beers, but it didn''t leave me in a state of euphoria.'),
                                                                    (17, 3, 'Nothing extraordinary, but it''s a decent choice if you''re in the mood for a simple beer.'),
                                                                    (17, 1, 'I expected a sweet and smooth experience, but it was more like drinking syrup.'),
                                                                    (17, 3, 'A beer that won''t wow you but won''t disappoint you either.'),
                                                                    (18, 1, 'It''s a hard pass'),
                                                                    (18, 2, 'Avoid this one if you value your taste buds'),
                                                                    (18, 1, 'It''s like drinking liquid wood. I prefer my beers with more balance and subtlety.'),
                                                                    (19, 1, 'Downtown Donut Brown is a unique brew, no doubt. The mix of grains, malts, and donuts is intriguing. However, I found it a tad too sweet for my liking. If you have a sweet tooth, this one might be worth a try.'),
                                                                    (19, 1, 'It''s a no for me.'),
                                                                    (19, 1, 'The dessert-like qualities are there, but the high ABV is somewhat hidden.'),
                                                                    (20, 4, 'Cocoa Nut Joe Porter is an interesting blend of flavors. The coconut and cacao notes are nice, and the coffee gives it a pleasant bitterness. It''s a good porter, but it doesn''t stand out in the crowded world of craft beer. Worth trying if you''re a fan of the style'),
                                                                    (20, 1, 'It''s a no for me.'),
                                                                    (20, 5, 'Definitely my favorite beer, and not just because of the cool name.'),
                                                                    (21, 3, 'Top Of The World boasts a complex profile, but it didn''t live up to my expectations. The dark fruit and malt flavors were there, but the high alcohol content was a bit overpowering. It lacked the balance I was hoping for. Not my top choice for a dark ale.'),
                                                                    (21, 5, 'A beer that makes me feel like I’’m on top of the world.'),
                                                                    (21, 4, 'I know it''s not super popular but I enjoy it.'),
                                                                    (22, 4, 'Black Satin is a chocolate lover''s dream. The dark chocolate and hazelnut blend beautifully, making it a delightful treat. Rich and indulgent, perfect for a winter evening. However, it could be a touch smoother. Still, it''s a solid porter.'),
                                                                    (22, 4, 'If you like chocolate, this is the beer for you!'),
                                                                    (22, 1, 'I''m a believer of not mixing sweets with beer.'),
                                                                    (23, 3, 'Body & Soul is a malt bomb, just as advertised. The caramelization process adds depth, and the full body is evident. However, it might be a bit too heavy for some. It''s a slow sipper, so be prepared to savor it.'),
                                                                    (23, 1, 'Gross. Idk what else to say.'),
                                                                    (23, 2, 'Meh.'),
                                                                    (24, 3, 'Honeysuckle Rose is a delightful Belgian Blond Ale. The subtle complexity and the hints of orange and lemon make it a pleasant choice. Not overly sweet, and the dry finish is quite satisfying. A solid representation of the style'),
                                                                    (24, 4, 'I love honeysuckle so this is just the beer for me.'),
                                                                    (24, 5, 'All around good beer'),
                                                                    (25, 5, 'Swishy Pants is an absolute delight for anyone who appreciates a well-crafted IPA. It pours a beautiful hazy golden hue and greets you with a burst of tropical fruit aromas as soon as you crack open the can. The taste is a symphony of juicy mango, pineapple, and a hint of citrus, all perfectly balanced with a subtle malt sweetness. Swishy Pants is the kind of beer that will make you a fan of hazy IPAs if you weren''t already. It''s an excellent choice for a sunny day or any time you want a refreshing and flavorful beer.'),
                                                                    (25, 1, 'Swishy Pants might have an interesting name, but it fails to deliver on its promise. From the first sip, it''s apparent that this beer is all hype and no substance. The hazy appearance is there, but the aroma is underwhelming, with only a faint hint of fruit. The taste is a disappointment, with a muddled blend of flavors that never quite come together. It''s as if they threw a bunch of random fruits into the brew without any thought to balance. The mouthfeel is mediocre at best, lacking the expected smoothness of a good hazy IPA. The finish leaves a lingering bitterness that''s more unpleasant than enjoyable. Overall, Swishy Pants is a letdown and not worth the hype.'),
                                                                    (25, 2, 'Would not drink again.'),
                                                                    (26, 4, 'Secret Machine-Triple is an extraordinary beer that showcases the artistry of brewing. It pours a gorgeous deep amber with a rich, creamy head that lingers. The aroma is an inviting mix of caramel, toffee, and a touch of spice.'),
                                                                    (26, 5, 'The taste is an explosion of flavor, with notes of dark fruits, Belgian yeast, and a subtle warming alcohol presence that''s just right for a triple. The mouthfeel is velvety and smooth, making each sip a true pleasure. The finish is long and complex, leaving you with a satisfying sweetness. Secret Machine-Triple is a masterpiece of a beer, perfect for sipping and savoring on a special occasion.'),
                                                                    (26, 1, 'It pours a murky brown with a weak, fizzy head that dissipates quickly. The aroma is overly sweet, almost cloying, and lacks the subtlety you''d expect from a Belgian triple.'),
                                                                    (27, 5, 'The taste is rich and decadent, with a perfect balance of bitter and sweet flavors'),
                                                                    (27, 5, 'The mouthfeel is silky smooth, making each sip a luxurious experience. The finish is long and satisfying, leaving you craving another sip. Hot Wax is a must-try for stout lovers.'),
                                                                    (27, 3, 'Decent beer.'),
                                                                    (28, 1, 'Futuristic Future tries too hard to be different and ends up losing its way.'),
                                                                    (28, 4, 'Futuristic Future is a forward-thinking beer that''s perfect for those looking to explore the cutting edge of brewing.'),
                                                                    (28, 4, 'The aroma is a burst of citrus and tropical fruit, promising a refreshing experience.'),
                                                                    (29, 4, 'Oak Barrel Stout is a true gem for lovers of rich, robust stouts. This beer pours a deep, velvety black with a creamy tan head that lingers.'),
                                                                    (29, 2, 'While it may appear impressive with its dark hue, the aroma is disappointingly weak, with only faint hints of roasted malt and no discernible oak notes.'),
                                                                    (29, 1, 'The finish is forgettable and leaves you wondering where all the promised oak flavor went.'),
                                                                    (30, 4, 'Double D is a double IPA that packs a punch in all the right ways.'),
                                                                    (30, 5, 'Double D is a delightful choice for hopheads looking for a bold and flavorful beer.'),
                                                                    (30, 3, 'The mouthfeel is overly carbonated and leaves a harsh sensation on the palate. Double D is a letdown for those seeking a well-crafted, enjoyable hoppy beer.'),
                                                                    (31, 5, 'Great beer for those looking to explore the world of Belgian ales, offering complexity and nuance in every sip.'),
                                                                    (31, 5, 'The taste is a harmonious blend of sweet malt, Belgian yeast, and a subtle floral note.'),
                                                                    (31, 3, 'Good to have with a burger and fries.'),
                                                                    (32, 1, 'Fell short of my expectations.'),
                                                                    (32, 2, 'Lacks the caramel richness you''d expect from an amber ale.'),
                                                                    (32, 4, 'Leaves you with a pleasant, malty aftertaste.'),
                                                                    (33, 4, 'Beach Escape is a perfect beach-day beer.'),
                                                                    (33, 3, 'It''s light, crisp, and has a hint of citrus.'),
                                                                    (33, 2, 'Like drinking water.'),
                                                                    (34, 4, 'Smooth and easy-going beer.'),
                                                                    (34, 2, 'Don''t get your hopes up for this beer.'),
                                                                    (34, 2, 'No standout qualities.'),
                                                                    (35, 5, 'Hawaii feel. The perfect choice for a summer day by the pool.'),
                                                                    (35, 3, 'Wai Ola is okay, but it doesn''t quite live up to the hype.'),
                                                                    (35, 1, 'Trash.'),
                                                                    (36, 3, 'A hearty oatmeal stout that''s good for a cozy evening indoors.'),
                                                                    (36, 3, 'Just another oatmeal stout.'),
                                                                    (36, 5, 'If you''re a fan of stouts, this one won''t disappoint.'),
                                                                    (37, 4, '7 Day IPA is a classic'),
                                                                    (37, 3, 'If you''ve had one IPA, you''ve pretty much had this one. It''s not bad, but it''s not exceptional either.'),
                                                                    (37, 2, 'Doesn''t bring anything new to the table.'),
                                                                    (38, 5, 'This beer made me ponder. Ya’’ll don’’t be pondering like I do.'),
                                                                    (38, 5, 'This beer made me feel wavy.'),
                                                                    (38, 5, 'Wavy Grainy is a unique and intriguing beer.'),
                                                                    (39, 2, 'Satisfied my thirst.'),
                                                                    (39, 2, 'The finish is relatively short and leaves you with a mild roasted aftertaste.'),
                                                                    (39, 4, 'Sin City Stout is a rich and indulgent treat for stout aficionados.'),
                                                                    (40, 3, 'Flute Lupulin is a decent choice for hop enthusiasts but may be overwhelming for those seeking a more balanced beer.'),
                                                                    (40, 1, 'Overly carbonated and leaves a prickly sensation on the tongue.'),
                                                                    (40, 3, 'A little bitter.'),
                                                                    (41, 5, 'Shadow is a mysterious and captivating beer that beckons you into the darkness.'),
                                                                    (41, 1, 'They forgot to add the flavor.'),
                                                                    (41, 3, 'Moderate beer.'),
                                                                    (42, 4, 'Exquisite taste.'),
                                                                    (42, 4, 'So good I had to call my friends and family and let them know.'),
                                                                    (42, 2, 'Texture. The name says it all.'),
                                                                    (43, 1, 'Big Stitch Nick. Big Stitch let down.'),
                                                                    (43, 2, 'Big Disappointment..'),
                                                                    (43, 5, 'Big bold flavor. I love it..'),
                                                                    (44, 4, 'This beer is a must-try!'),
                                                                    (44, 2, 'The taste is a mishmash of flavors that seem thrown together without much thought.'),
                                                                    (44, 1, 'This was a fun drink.'),
                                                                    (45, 4, 'Reliable choice for an all around good beer!'),
                                                                    (45, 3, 'The taste is a mishmash of flavors that seem thrown together without much thought.'),
                                                                    (45, 4, 'This was a fun drink.'),
                                                                    (46, 4, 'Rye Not? is a delightful and unique beer that stands out from the crowd.'),
                                                                    (46, 1, 'It''s is abrupt and leaves an odd aftertaste.'),
                                                                    (46, 5, 'Rye Not? is an excellent choice for those seeking a flavorful and well-crafted beer with a rye kick.'),
                                                                    (47, 4, 'Lush flavor profile.'),
                                                                    (47, 5, 'Rich blend of exotic spices, tropical fruits, and a subtle earthiness'),
                                                                    (47, 3, 'Interesting drink for sure.'),
                                                                    (48, 4, 'Smooth Jazz is the beer equivalent of a mellow, late-night jazz session.'),
                                                                    (48, 4, 'Exudes sophistication and relaxation.'),
                                                                    (48, 3, 'This brew is perfect for unwinding after a long day, setting the mood for a tranquil evening.'),
                                                                    (49, 2, 'Ok for a lite beer.'),
                                                                    (49, 4, 'This beer manages to deliver a surprisingly robust taste profile while keeping the calories in check.'),
                                                                    (49, 3, 'Ideal choice for those seeking a lighter yet flavorful beer.'),
                                                                    (50, 5, 'This modern take on the classic Gose style offers a delightful twist with its bold flavors of sea salt, coriander, and a tangy citrus zing.'),
                                                                    (50, 1, 'You couldn''t pay me enough to drink this again.'),
                                                                    (50, 4, 'Delicious beer.'),
                                                                    (51, 3, 'The taste is alright, with a decent balance of hops and malt, although it doesn''t particularly stand out.'),
                                                                    (51, 2, 'I really didn''t enjoy Lupulin Enlightenment.'),
                                                                    (51, 3, 'Okay-ish.'),
                                                                    (52, 4, 'Beer that lives up to its unique name!'),
                                                                    (52, 2, 'Superfluous Nomenclature is an okay imperial stout.'),
                                                                    (52, 2, 'I was really disappointed.'),
                                                                    (53, 1, 'Beer that lives up to its unique name!'),
                                                                    (53, 2, 'Superfluous Nomenclature is an okay imperial stout..'),
                                                                    (53, 2, 'I was really disappointed.'),
                                                                    (54, 1, 'Krauch''s Creation is a masterpiece! This beer is a true work of art, showcasing the brewer''s talent and creativity.'),
                                                                    (54, 2, 'It''s a solid choice if you''re looking for a traditional amber ale.'),
                                                                    (54, 2, 'I was really disappointed.'),
                                                                    (55, 5, 'Eloquation is a true gem in the world of craft beers.'),
                                                                    (55, 5, 'The taste is a symphony of flavors, with notes of clove, banana, and a subtle hint of citrus.'),
                                                                    (55, 4, 'It''s wonderfully complex yet incredibly drinkable.'),
                                                                    (56, 3, 'Not impressed.'),
                                                                    (56, 5, 'XII APA is a real winner!'),
                                                                    (56, 2, 'I found XII APA to be quite forgettable.'),
                                                                    (57, 1, 'Your Mom sucks.'),
                                                                    (57, 2, 'Your Mom was a disappointment.'),
                                                                    (57, 5, 'Your Mom is a cheeky and surprisingly good beer! This brown ale pours a deep amber with a sweet, malty aroma that''s inviting. The taste is pleasantly smooth, featuring caramel and toffee notes with a hint of nuttiness. It''s a playful and enjoyable brew that leaves you with a smile on your face.'),
                                                                    (58, 4, 'Sundown Saison is a delightful and refreshing farmhouse ale.'),
                                                                    (58, 2, 'I was expecting more from a saison, this one missed the mark for me.'),
                                                                    (58, 1, 'It had a strange aftertaste that I found off-putting, and the flavors didn''t come together well.'),
                                                                    (59, 1, 'Orange Street Ale is not good.'),
                                                                    (59, 2, 'Too sweet.'),
                                                                    (59, 4, 'A sweet treat.'),
                                                                    (60, 5, 'A small joy.'),
                                                                    (60, 3, 'I think the name is fitting for this beer. It''s good but I wish it had more pizazz.'),
                                                                    (60, 2, 'I would not recommend this beer to anyone in my life. Not even my worst enemy.'),
                                                                    (61, 5, 'Smooth beer for an oat milk lover!'),
                                                                    (61, 5, 'This beer tricks my brain into thinking I''m being healthy and I love it.'),
                                                                    (61, 4, 'This beer is a solid choice for a fine afternoon.'),
                                                                    (62, 5, 'Kiamensi is, hands down, my favorite beer!'),
                                                                    (62, 4, 'This beer was recommended to be my a neighbor, and I''m glad I tried it because I was pleasantly surprised.'),
                                                                    (62, 1, 'This beer made me want to become sober.'),
                                                                    (63, 1, 'They could use this beer to clean with and maybe it would be worth something.'),
                                                                    (63, 3, 'Overpriced for the quality.'),
                                                                    (63, 5, 'Hopworts Express is boss.'),
                                                                    (64, 4, 'This was recommended to me by a friend - great choice!!'),
                                                                    (64, 5, 'This beer is so good they had to cut me off last night.'),
                                                                    (64, 3, 'A fine beer for a fine brewery.'),
                                                                    (65, 5, 'BEST BEER I HAVE EVER HAD'),
                                                                    (65, 2, 'Mediocre beer. Not my favorite'),
                                                                    (65, 5, 'I''ve tasted better');




COMMIT TRANSACTION;
