BEGIN TRANSACTION;

-- Created users to put it in the database
INSERT INTO users (username,password_hash,role) VALUES ('user','$2a$08$UkVvwpULis18S19S5pZFn.YHPZt3oaqHZnDwqbCW9pft6uFtkXKDC','ROLE_USER');
INSERT INTO users (username,password_hash,role) VALUES ('admin','$2a$08$UkVvwpULis18S19S5pZFn.YHPZt3oaqHZnDwqbCW9pft6uFtkXKDC','ROLE_ADMIN');

-- Created breweries to put in the database
INSERT INTO breweries (brewery_name, contact_info, brewery_history, operating_hours, brewery_img_url, brewery_address, brewery_city, brewery_state, brewery_zip, is_active) VALUES ('Autumn Arch', '(302) 294-1126', 'Local brewery located in Delaware. Opened in 2023.', 'Wed: 4-9pm, Thurs: 3-10pm, Fri: 12-10pm, Sat: 12-10pm, Sun: 12-8pm', 'https://s3-media0.fl.yelpcdn.com/bphoto/9UOIKbaZNCsSQ0f0Cwi2LA/348s.jpg', '810 Pencader Drive Suite C', 'Newark', 'DE', 19702, false);
INSERT INTO breweries (brewery_name, contact_info, brewery_history, operating_hours, brewery_img_url, brewery_address, brewery_city, brewery_state, brewery_zip, is_active) VALUES ('Southern Ohio Brewing', 'https://www.southernohiobrewing.com/welcome-91521', 'Family owned and operated, Southern Ohio Brewing is a great place for getting together with family, friends or coworkers. We have 12-14 rotating taps featuring a wide range of  craft beer styles from our on-site brewhouse. Wine and our own house made hard seltzer are also available. ', 'Wed: 4-9pm, Thurs: 4-9pm, Fri: 3-10pm, Sat: 12-10pm, Sun: 12-8pm', 'https://images.squarespace-cdn.com/content/v1/5e8cbbecfb706f4f214ce102/c0376ed6-cf3b-4e49-b238-4977d9a3e5eb/taproom.jpg?format=2500w', '818 Factory Rd', 'Beavercreek', 'OH', 45434, true);
INSERT INTO breweries (brewery_name, contact_info, brewery_history, operating_hours, brewery_img_url, brewery_address, brewery_city, brewery_state, brewery_zip, is_active) VALUES ('Miller Brewing Company', 'dataprotection@molsoncoors.com', 'In 1786, English immigrant John Molson founded Canada’s oldest beer brewery on the banks of the St. Lawrence River in Montreal. He wrote, “My beer has been universally well-liked beyond my most sanguine expectations.” The legacy continues seven generations later with brands like Molson Canadian, which was first brewed in 1959 and remains today one of Canada’s most iconic and best-selling beers.', 'Thurs: 10am-5pm, Fri: 10am-5pm', 'https://www.molsoncoors.com/sites/molsonco/files/2022-05/Brewery_Milwaukee_1920x768_v2.jpg', '4000 W. State Street', 'Milwaukee', 'WI', 53208, true);
INSERT INTO breweries (brewery_name, contact_info, brewery_history, operating_hours, brewery_img_url, brewery_address, brewery_city, brewery_state, brewery_zip, is_active) VALUES ('Iron Hill Brewery', '(302) 472-2739', 'Kevin Finn, one of those Delaware locals, receives a homebrewing kit from his wife for his wife for his birthday.What starts as a hobby soon becomes a passion', 'Mon: 11am-10pm, Tues: 11am-10pm, Wed: 11am-10pm, Thurs: 11am-10pm, Fri: 11am-10:30pm, Sat: 11am-10:30pm, Sun: 11am-9pm', 'https://assets.simpleviewinc.com/simpleview/image/upload/c_limit,q_75,w_1200/v1/crm/wilmington/RIVERFRONT_Iron-Hill-Brewery-Exterior-355995005056b3a_355997a2-5056-b3a8-495081b6d5a23b1e.jpg', '620 JUSTISON ST', 'Wilmington', 'DE', 19801, true);

-- Created beers to put in the database
INSERT INTO beers (brewery_id, beer_name, beer_description, abv, ibu, beer_rating, beer_review, beer_img_url, beer_type) VALUES ('1', 'Pumpkin Loaf', 'It’s all the classic fall spices forged atop a smooth & respectable German Bock backbone.  Strong layers of pumpkin bread and autumn vibes fade into a sweet caramel finish.', 7.1, 35, 4, 'This Jawn good bro', 'https://vinepair.com/wp-content/uploads/2020/10/weask_pumpkinale_social.jpg', 'Ale');
INSERT INTO beers (brewery_id, beer_name, beer_description, abv, ibu, beer_rating, beer_review, beer_img_url, beer_type) VALUES ('2', 'Cloudy Not Hazy', 'A traditional German style wheat beer brewed with a low flocculating German yeast strain that creates notes of clove and banana. This yeast produces a beer with a cloudy appearance long before hazy beers became a thing.', 5.0, 10, 3, 'This stuff be bussin!', 'https://upload.wikimedia.org/wikipedia/commons/thumb/d/df/Hefeweizen_Glass.jpg/330px-Hefeweizen_Glass.jpg', 'Wheat Beer');
INSERT INTO beers (brewery_id, beer_name, beer_description, abv, ibu, beer_rating, beer_review, beer_img_url, beer_type) VALUES ('3', 'Blue Moon', 'A wheat beer brewed with orange peel for a subtle sweetness and bright, citrus aroma. Blue Moon® Belgian White Belgian-Style Wheat Ale is garnished with an orange slice to heighten the citrus aroma and taste.', 5.4, 13, 5, 'Best Beer on god!', 'https://siestaspirits.com/cdn/shop/products/blue_moon_bot_glass.jpg?v=1571264406', 'Wheat Ale');
INSERT INTO beers (brewery_id, beer_name, beer_description, abv, ibu, beer_rating, beer_review, beer_img_url, beer_type) VALUES ('4', 'Iron Hill Light Lager', 'Our lightest beer. Brewed to give a crisp, clean, refreshing taste with very subtle malt and hop flavor.', 4.0, 10, 2, 'This Jawn triflin bruh!', 'https://media-cdn.tripadvisor.com/media/photo-m/1280/16/27/86/44/iron-hill-light-lager.jpg', 'Lager');

COMMIT TRANSACTION;
